#!/usr/bin/env python3
"""
Export web-optimized copies of your original photos.

    python3 scripts/optimize.py                 # originals/ -> photos/
    python3 scripts/optimize.py path/to/folder  # any folder -> photos/
    python3 scripts/optimize.py path/to/folder winter-fest
                                                # any folder -> photos/winter-fest/

A subfolder of originals/ (e.g. originals/winter-fest/) is exported to the
subfolder of photos/ with the same name (photos/winter-fest/), but only if
that folder already exists. Other subfolders, like originals/unused/, are
left alone.

For every JPEG/PNG/TIFF/WebP image in the source folder it:
  * applies the camera's EXIF rotation, then strips all metadata
    (including GPS location) from the copy,
  * converts to sRGB-safe RGB and resizes to 2000px on the long edge
    (smaller images are left at their size),
  * saves a progressive JPEG at quality 82 into photos/ with a
    lowercase .jpg extension.

Afterwards it rewrites photos/sizes.js, a generated list of each photo's
pixel size that the page uses to reserve space and avoid layout shift.
Never edit sizes.js by hand; just re-run this script.

Requires Pillow:  python3 -m pip install Pillow
"""

import json
import sys
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.exit("Pillow is not installed. Run:  python3 -m pip install Pillow")

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "photos"
LONG_EDGE = 2000
QUALITY = 82
EXTENSIONS = {".jpg", ".jpeg", ".png", ".tif", ".tiff", ".webp"}


def export(src: Path, dest: Path) -> None:
    with Image.open(src) as im:
        icc = im.info.get("icc_profile")
        im = ImageOps.exif_transpose(im)
        if im.mode != "RGB":
            im = im.convert("RGB")
        im.thumbnail((LONG_EDGE, LONG_EDGE), Image.LANCZOS)
        options = dict(quality=QUALITY, optimize=True, progressive=True)
        if icc:
            options["icc_profile"] = icc  # keep colour accurate; no EXIF
        im.save(dest, "JPEG", **options)


def write_sizes() -> None:
    sizes = {}
    for f in sorted(OUT_DIR.rglob("*")):
        if f.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}:
            with Image.open(f) as im:
                sizes[f.relative_to(OUT_DIR).as_posix()] = list(im.size)
    lines = [f"  {json.dumps(name)}: [{w}, {h}]" for name, (w, h) in sizes.items()]
    body = "{\n" + ",\n".join(lines) + "\n}"
    (OUT_DIR / "sizes.js").write_text(
        "// Generated by scripts/optimize.py. Do not edit by hand.\n"
        f"window.PHOTO_SIZES = {body};\n"
    )
    print(f"Wrote photos/sizes.js ({len(sizes)} photos)")


def optimize_folder(src_dir: Path, out_dir: Path) -> None:
    out_dir.mkdir(exist_ok=True)
    files = sorted(p for p in src_dir.iterdir() if p.suffix.lower() in EXTENSIONS)
    print(f"{src_dir.name}/ -> {out_dir.relative_to(ROOT)}/")
    if not files:
        print("  (no images)")
    for src in files:
        dest = out_dir / (src.stem + ".jpg")
        if dest.exists() and dest.stat().st_mtime >= src.stat().st_mtime:
            print(f"  skip  {dest.name} (up to date)")
            continue
        export(src, dest)
        kb = dest.stat().st_size / 1024
        print(f"  saved {dest.name}  {kb:,.0f} KB")


def main() -> None:
    src_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "originals"
    if not src_dir.is_dir():
        sys.exit(f"Source folder not found: {src_dir}")

    if len(sys.argv) > 2:
        optimize_folder(src_dir, OUT_DIR / sys.argv[2])
    else:
        optimize_folder(src_dir, OUT_DIR)
        for sub in sorted(d for d in src_dir.iterdir() if d.is_dir()):
            if (OUT_DIR / sub.name).is_dir():
                optimize_folder(sub, OUT_DIR / sub.name)

    write_sizes()


if __name__ == "__main__":
    main()
